# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGUIfile(object):
    def setupUi(self, mainGUIfile):
        mainGUIfile.setObjectName("mainGUIfile")
        mainGUIfile.resize(800, 400)
        mainGUIfile.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"")
        self.widget = QtWidgets.QWidget(mainGUIfile)
        self.widget.setGeometry(QtCore.QRect(20, -1, 851, 431))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-20, -1, 800, 401))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/project 1/png/deepLearning.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(510, 150, 91, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Century Gothic\";\n"
"font: 700 9pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.215909, y1:0.505682, x2:0.659091, y2:0.511364, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 104, 255));\n"
"border-radius:10px;\n"
"border-top : 2px solid blue;\n"
"border-bottom : 2px solid black;\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0.159091, y1:0.534, x2:0.670455, y2:0.551136,     stop:0 rgba(24, 24, 24, 255), stop:0.977273 rgba(0, 0, 96, 255), stop:1 rgba(0, 0, 96, 255));\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-position: calc(100% - 10px)center;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.153409, y1:0.460227, x2:0.789773, y2:0.511, stop:0 rgba(7, 7, 7, 255), stop:1 rgba(0, 0, 121, 255));\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 220, 91, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"    color: rgb(255, 255, 255);\n"
"font: 10pt \"Century Gothic\";\n"
"font: 700 9pt \"Segoe UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0.215909, y1:0.505682, x2:0.659091, y2:0.511364, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 104, 255));\n"
"border-radius:10px;\n"
"border-top : 2px solid blue;\n"
"border-bottom : 2px solid black;\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0.159091, y1:0.534, x2:0.670455, y2:0.551136,     stop:0 rgba(24, 24, 24, 255), stop:0.977273 rgba(0, 0, 96, 255), stop:1 rgba(0, 0, 96, 255));\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-position: calc(100% - 10px)center;\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.153409, y1:0.460227, x2:0.789773, y2:0.511, stop:0 rgba(7, 7, 7, 255), stop:1 rgba(0, 0, 121, 255));\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 330, 61, 51))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-position: calc(100% - 10px)center;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/project 1/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(370, 60, 281, 41))
        self.label_2.setStyleSheet("background-color: transparent;\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/project 1/png/logo-no-background.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(mainGUIfile)
        QtCore.QMetaObject.connectSlotsByName(mainGUIfile)

    def retranslateUi(self, mainGUIfile):
        _translate = QtCore.QCoreApplication.translate
        mainGUIfile.setWindowTitle(_translate("mainGUIfile", "mainGUIfile"))
        self.pushButton.setText(_translate("mainGUIfile", "START"))
        self.pushButton_2.setText(_translate("mainGUIfile", "LOG IN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGUIfile = QtWidgets.QWidget()
    ui = Ui_mainGUIfile()
    ui.setupUi(mainGUIfile)
    mainGUIfile.show()
    sys.exit(app.exec_())
