# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signupWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 600)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.119318, y1:0.761, x2:0.897727, y2:0.278409, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 82, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(140, 40, 201, 71))
        self.label_2.setStyleSheet("font: 700 24pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 160, 341, 51))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.125, y1:0.739, x2:0.732955, y2:0.238636, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 47, 255));\n"
"border-radius : 1px;\n"
"border-bottom: 1px solid rgb(139, 139, 139);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 250, 341, 51))
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.125, y1:0.739, x2:0.732955, y2:0.238636, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 47, 255));\n"
"border-radius : 1px;\n"
"border-bottom: 1px solid rgb(139, 139, 139);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 340, 341, 51))
        self.lineEdit_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.125, y1:0.739, x2:0.732955, y2:0.238636, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 47, 255));\n"
"border-radius : 1px;\n"
"border-bottom: 1px solid rgb(139, 139, 139);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(310, 480, 111, 41))
        self.pushButton.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 255, 255);\n"
"font: 700 11pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(90, 420, 311, 31))
        self.label_3.setStyleSheet("color: rgb(252, 0, 0);\n"
"font: 700 10pt \"Segoe UI\";")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 480, 91, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 255, 255);\n"
"font: 700 11pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Sign Up"))
        self.lineEdit.setPlaceholderText(_translate("Form", " Email"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", " Password"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", " Confirm Password"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_2.setText(_translate("Form", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
